{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kumomta.fullname" . }}
spec:
  endpoints:
    - path: /metrics
      targetPort: 8080
      {{- with .Values.serviceMonitor.basicAuth }}
      basicAuth:
      {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kumomta.selectorLabels" . | nindent 6 }}
{{- end }}
