apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kumomta.fullname" . }}-tsa
  labels:
    {{- include "kumomta.tsaLabels" . | nindent 4 }}
spec:
  serviceName: "{{ include "kumomta.fullname" . }}-tsa"
  podManagementPolicy: Parallel # https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#parallel-pod-management
  {{- if not .Values.tsa.autoscaling.enabled }}
  replicas: {{ .Values.tsa.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kumomta.tsaSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/kumo-configs: {{ (.Files.Get "kumo-configs/tsa_init.lua") | sha256sum }}
      {{- with .Values.tsaPodAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kumomta.tsaLabels" . | nindent 8 }}
        {{- with .Values.tsa.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kumomta.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-tsa
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.tsa.deployment.command }}
          command:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tsa.deployment.args }}
          args:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.tsa.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.tsa.service.httpPort }}
              protocol: TCP
          {{- with .Values.tsa.lifecycleHook }}
          lifecycle:
            {{- toYaml . | nindent 12}}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.tsa.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.tsa.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.tsa.resources | nindent 12 }}
          {{- with .Values.tsa.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.tsa.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
# TODO: do we need separate affinity, etc for tsa ?
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tsa.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  {{- with .Values.tsa.volumeClaimTemplates}}
  volumeClaimTemplates:
    {{- toYaml . | nindent 2 }}
  {{- end }}
