{{- if .Values.tsa.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kumomta.fullname" . }}-tsa
  labels:
    {{- include "kumomta.tsaLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kumomta.fullname" . }}-tsa
  minReplicas: {{ .Values.tsa.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.tsa.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.tsa.autoscaling.targetCPUUtilizationPercentage }}
    - type: ContainerResource
      containerResource:
        name: cpu
        container: {{ .Chart.Name }}-tsa
        target:
          type: Utilization
          averageUtilization: {{ .Values.tsa.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.tsa.autoscaling.targetMemoryUtilizationPercentage }}
    - type: ContainerResource
      containerResource:
        name: memory
        container: {{ .Chart.Name }}-tsa
        target:
          type: Utilization
          averageUtilization: {{ .Values.tsa.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.tsa.autoscaling.additionalMetrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
